### ISSUE TITLE
Rider 2020.3 EAP releases break the search provider

### ISSUE THREAD

**Issue by axelgenus** [lunaryorn/jetbrains-search-provider#11]
Recently I was playing around Rider 2020.3 EAP and I noticed that the search provider stopped working (only for) for Rider. I investigated a bit today and I noticed that the _recentSolutions.xml_ file changed structure. Basically the line 110 of find_projects.py won't work with Rider 2020.3:

`document.findall('.//option[@name="recentPaths"]/list/option'))`

should now be something like:

`document.findall('.//option[@name="additionalInfo"]/list/option'))`

I am still unsure whether this change applies to all JetBrains product but I have the complete toolbox so I will keep this issue updated.

**Comment by axelgenus** [comment]
I just finished testing with the latest Rider EAP(7) and it seems to be working back just fine. Probably it was a regression added to the previous EAP version.

**Comment by lunaryorn** [comment]
@axelgenus 2020.03 did change the format; I released v11 yesterday to address this issue.  Would you mind to test it with Rider?

**Comment by axelgenus** [comment]
Rider 2020.3 has not been released yet. I reopen the issue. If you want you can assign it to me.

**Comment by Spurlos** [comment]
Looks like it a change across all JetBrains IDEs, as PHPStorm 2020.3 project also stopped showing in search.

**Comment by lunaryorn** [comment]
Did you update to the latest release?

**Comment by lunaryorn** [comment]
I'm sorry but that's out of my control; extensions go through a mandatory review process which can take days, even weeks sometimes.  I uploaded the new release when I tagged it; there's nothing more I can do.

As said in the README, if you'd like to have updates fast you need to watch releases and manually install the attached ZIP file.

**Comment by lunaryorn** [comment]
Assuming that rider works I'm closing this now.
