### ISSUE TITLE
Only work when IDE is not running.

### ISSUE THREAD

**Issue by qwIvan** [lunaryorn/jetbrains-search-provider#15]
If there is a IDE process running, the second instance can not be opened.

**Comment by qwIvan** [comment]
I found out that the opened window needs to be out of focus.

**Comment by lunaryorn** [comment]
I don't know what you mean: I can perfectly open other projects in IDEA, no matter what window is focused.

In any case, I can't reproduce this, and the extension behaves as I expect it to, and it has little control over IDEA startup anyways.  I'm closing this issue; please do open a pull request if there's anything you'd like to have fixed.
