### ISSUE TITLE
Gnome 40

### ISSUE THREAD

**Issue by t0kieu** [lunaryorn/jetbrains-search-provider#19]
Hi,
please add support for gnome 40 and JetBrains IDEs in version 2021.1

**Comment by qwIvan** [comment]
+1

**Comment by lunaryorn** [comment]
Why would 2021.1 no longer be supported?

As for Gnome 40 that won't happen until I start using Gnome 40 myself, so if you need it now or any time soon you'll need to make a pull request.

**Comment by lunaryorn** [comment]
I am closing this issue because too me it's not currently actionable. Please do feel free to open a pull request.

**Comment by lunaryorn** [comment]
@t0kieu @qwIvan For Gnome 40 support please see https://github.com/lunaryorn/gnome-search-providers-jetbrains.

I'll no longer maintain this Gnome extension; and have archived this repository.
