### ISSUE TITLE
Register as proper search provider to allow configuration of the search result order

### ISSUE THREAD

**Issue by atomicptr** [lunaryorn/jetbrains-search-provider#6]
The plugin should come up as a search provider in this little window (Settings > Search):

![image](https://user-images.githubusercontent.com/674705/90386419-d742b700-e084-11ea-962d-0d61474bfc5b.png)

This would allow me to change the order in which search results appear in. For instance currently I often get something else appear before my project search:

![image](https://user-images.githubusercontent.com/674705/90386645-2983d800-e085-11ea-9bd3-1325b05a0ec6.png)

I haven't done much research into this and don't even know if this is possible at all, but it would be neat.

Tyvm

**Comment by lunaryorn** [comment]
I don't think it's possible, but in any case it's not too important to me, so if you'd like to have this you'll need to make a pull request.

Closing since I won't do this myself.

**Comment by atomicptr** [comment]
I'll look into it :)

**Comment by lunaryorn** [comment]
@atomicptr I created <https://github.com/lunaryorn/gnome-search-providers-jetbrains> to replace this extension; it's a proper search provider which appears in the settings app and allows to change the order of search results.
