### ISSUE TITLE
Request: Add PhpStorm snap support

### ISSUE THREAD

**Issue by Spurlos** [lunaryorn/jetbrains-search-provider#7]
Would be glad to see PhpStorm snap support.

Snap is the new way of installing software in Ubuntu 20.04 out of the box, so support for snap packages would be appreciated. I see that some other IDEs have snap support, so it looks like implementation is already in place, just not for all IDEs.

**Comment by lunaryorn** [comment]
You'll need to make a pull request; I don't use PHP Storm.  Closing since I myself won't add this; I'll merge a pull request however.
